#!/usr/bin/env ruby
# frozen_string_literal: true

# aggregate.rb — rebuild this repo's tpkg-registry.yaml from the
# feedstocks' own registries (spec 37 §6: the official registry is a
# GENERATED AGGREGATE; each feedstock's tpkg-registry.yaml stays the
# authored authority — SSOT).
#
#   ruby tools/aggregate.rb           regenerate tpkg-registry.yaml in place
#   ruby tools/aggregate.rb --check   parity assertion: exit 1 when the
#                                     committed file differs from a fresh
#                                     regeneration (never hand-edit it)
#
# Rows flow VERBATIM (values) — including `status: withdrawn`. A payload
# name carried by several feedstocks aggregates once when every row is
# identical (DEPENDS-closure mirroring); DIVERGENT rows for one name
# abort the run, naming the carriers (never a priority pick — the
# aggregate is internally unambiguous by construction). Network reads are
# plain HTTPS GETs of raw.githubusercontent.com (public repos;
# GITHUB_TOKEN is used when present, raising the rate budget).

require "net/http"
require "uri"
require "yaml"

ORG = "tebako-packages"
ROOT = File.expand_path("..", __dir__)
FEEDSTOCKS = File.join(ROOT, "feedstocks.txt")
OUT = File.join(ROOT, "tpkg-registry.yaml")

def fetch(url)
  uri = URI(url)
  req = Net::HTTP::Get.new(uri)
  req["Authorization"] = "Bearer #{ENV['GITHUB_TOKEN']}" if ENV["GITHUB_TOKEN"]
  res = Net::HTTP.start(uri.host, uri.port, use_ssl: true) { |h| h.request(req) }
  return res.body if res.is_a?(Net::HTTPSuccess)

  raise "GET #{url} → #{res.code} #{res.message}"
end

def feedstocks
  File.readlines(FEEDSTOCKS, chomp: true)
    .map(&:strip)
    .reject { |line| line.empty? || line.start_with?("#") }
end

# One "payloads: [row]" dump per row keeps Psych's block style; dropping
# the "---" and "payloads:" lines leaves the bare "- name: …" entry that
# nests under the document's single payloads: key (unindented sequence,
# the same style the feedstocks author), with a source comment above it.
def render(rows)
  out = +"schema_version: 1\n"
  out << "# GENERATED by tools/aggregate.rb from the feedstocks' own registries —\n"
  out << "# NEVER hand-edit (the --check leg asserts parity). The authored authority\n"
  out << "# for every row is the named feedstock's own tpkg-registry.yaml.\n"
  out << "payloads:\n"
  rows.each do |source, row|
    out << "# source: #{ORG}/#{source}\n"
    out << { "payloads" => [row] }.to_yaml.lines.drop(2).join
  end
  out
end

def build
  # name => [row, [sources]] — a name carried by several feedstocks is
  # fine ONLY when every carrier's row is identical (a DEPENDS-closure
  # mirror, e.g. metanorma mirroring the inkscape toolkit it requires);
  # the aggregate emits it once with all sources credited. Divergent
  # rows for one name are a real fork — the run aborts, naming the
  # carriers (never a priority pick).
  by_name = {}
  order = []
  feedstocks.each do |repo|
    doc = YAML.safe_load(fetch("https://raw.githubusercontent.com/#{ORG}/#{repo}/HEAD/tpkg-registry.yaml"))
    unless doc.is_a?(Hash) && doc["schema_version"] == 1 && doc["payloads"].is_a?(Array)
      raise "#{repo}: tpkg-registry.yaml is not a schema_version: 1 payload registry"
    end

    doc["payloads"].each do |row|
      name = row.fetch("name") { raise "#{repo}: a payload row carries no name" }
      if (existing = by_name[name])
        unless existing[0] == row
          raise "divergent rows for payload '#{name}': carried by #{(existing[1] + [repo]).join(', ')} " \
                "but the rows differ — one payload name, one truth; reconcile the feedstocks"
        end

        existing[1] << repo
      else
        by_name[name] = [row, [repo]]
        order << name
      end
    end
    warn "read #{doc['payloads'].length} payload(s) from #{repo}"
  end
  render(order.map do |name|
    row, sources = by_name[name]
    warn "aggregated #{name} (#{sources.join(', ')})"
    [sources.join(", "), row]
  end)
end

generated = build
if ARGV == ["--check"]
  committed = File.exist?(OUT) ? File.read(OUT) : ""
  if committed == generated
    puts "parity OK — tpkg-registry.yaml matches a fresh regeneration"
  else
    warn "PARITY FAILURE: tpkg-registry.yaml differs from a fresh regeneration"
    warn "  run: ruby tools/aggregate.rb   (never hand-edit the file)"
    exit 1
  end
else
  File.write(OUT, generated)
  puts "wrote #{OUT} (#{generated.scan(/^- name:/).size} payload row(s))"
end
